language: node_js
node_js: 10
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: tuscnetwork/tusc-ui
        - WALLET_REPO: tuscnetwork/wallet.tusc.network
        - STAGING_REPO: tuscnetwork/tusc-ui-staging
        - DEVELOP_REPO: tuscnetwork/develop.tusc.network
        - CXX=g++-4.8
        - secure: ""
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    - npm ci
script: "./build.sh"
after_success: "./deploy.sh"
deploy:
    provider: releases
    tag_name: $TRAVIS_TAG
    name: $TRAVIS_TAG
    body: Automated release from Travis CI with added files from AppVeyor build
    api_key:
        secure: ""
    file_glob: true
    file:
        - build/binaries/TUSC*
        - build/release-checksums-*
    skip_cleanup: true
    draft: true
    on:
        repo: tuscnetwork/tusc-ui
        tags: true
