language: node_js
node_js: 10
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
env:
    global:
        - GITHUB_REPO: tusc/tusc-ui
        - WALLET_REPO: tusc/wallet.tusc.org
        - STAGING_REPO: tusc/tusc-ui-staging
        - DEVELOP_REPO: tusc/develop.tusc.org
        - CXX=g++-4.8
        - secure: ""
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8
            - icnsutils
            - graphicsmagick
            - xz-utils
install:
    - npm ci
script:
    - "./build.sh"
after_success: "./deploy.sh"
deploy:
    - provider: releases
      tag_name: "$TRAVIS_TAG"
      name: "$TRAVIS_TAG"
      body: "Automated release from Travis CI with added files from AppVeyor build"
      api_key:
          secure: ""
      file_glob: true
      file:
          - build/binaries/tusc*
          - build/release-checksums-*
      skip_cleanup: true
      draft: true
      on:
          repo: TUSCNetwork/tusc-ui
          tags: true
before_install:
    - openssl aes-256-cbc -K $encrypted_844f3e8bd137_key -iv $encrypted_844f3e8bd137_iv
      -in set_snap_token.sh.enc -out set_snap_token.sh -d
    - chmod +x set_snap_token.sh
    - source ./set_snap_token.sh
